// Stable application error codes. Do not rename existing values; add new ones.
// Documented in docs/JobTinder-V0.1-技术架构与代码边界.md §11

export const AppErrorCode = {
  // AUTH_*
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_ROLE_MISSING: 'AUTH_ROLE_MISSING',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',

  // VERSION_*
  VERSION_MISMATCH: 'VERSION_MISMATCH',
  VERSION_EXPECTED_MISSING: 'VERSION_EXPECTED_MISSING',

  // IDEMPOTENT_*
  IDEMPOTENT_DUPLICATE: 'IDEMPOTENT_DUPLICATE',
  IDEMPOTENT_KEY_MISMATCH: 'IDEMPOTENT_KEY_MISMATCH',

  // PROFILE_*
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_NOT_CONFIRMED: 'PROFILE_NOT_CONFIRMED',
  PROFILE_DRAFT_STALE: 'PROFILE_DRAFT_STALE',
  PROFILE_PAUSED: 'PROFILE_PAUSED',
  PROFILE_ROLE_CONFLICT: 'PROFILE_ROLE_CONFLICT',

  // COMPANY_*
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
  COMPANY_NOT_VERIFIED: 'COMPANY_NOT_VERIFIED',
  COMPANY_MEMBERSHIP_REQUIRED: 'COMPANY_MEMBERSHIP_REQUIRED',

  // JOB_*
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_NOT_ACTIVE: 'JOB_NOT_ACTIVE',
  JOB_EXTERNAL_ONLY: 'JOB_EXTERNAL_ONLY',
  JOB_ALREADY_CLOSED: 'JOB_ALREADY_CLOSED',

  // INTEREST_*
  INTEREST_ALREADY_EXISTS: 'INTEREST_ALREADY_EXISTS',
  INTEREST_NOT_PENDING: 'INTEREST_NOT_PENDING',
  INTEREST_EXPIRED: 'INTEREST_EXPIRED',
  INTEREST_ACTOR_MISMATCH: 'INTEREST_ACTOR_MISMATCH',
  INTEREST_SAME_SIDE: 'INTEREST_SAME_SIDE',

  // MATCH_*
  MATCH_ALREADY_EXISTS: 'MATCH_ALREADY_EXISTS',
  MATCH_VERSION_INVALID: 'MATCH_VERSION_INVALID',
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',

  // CONTACT_*
  CONTACT_NOT_SHARED: 'CONTACT_NOT_SHARED',
  CONTACT_MATCH_REQUIRED: 'CONTACT_MATCH_REQUIRED',

  // NOTIFY_*
  NOTIFY_DEDUPE_HIT: 'NOTIFY_DEDUPE_HIT',
  NOTIFY_TOO_MANY_ATTEMPTS: 'NOTIFY_TOO_MANY_ATTEMPTS',
  NOTIFY_DELIVERY_FAILED: 'NOTIFY_DELIVERY_FAILED',

  // CRAWL_*
  CRAWL_SOURCE_BLOCKED: 'CRAWL_SOURCE_BLOCKED',
  CRAWL_PARSE_FAILED: 'CRAWL_PARSE_FAILED',

  // AI_*
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  AI_PROVIDER_UNKNOWN: 'AI_PROVIDER_UNKNOWN',

  // TRUST_*
  TRUST_BLOCKED: 'TRUST_BLOCKED',
  TRUST_REPORT_DUPLICATE: 'TRUST_REPORT_DUPLICATE',

  // DB_* — infrastructure availability, surfaced to user as friendly retry prompt
  DB_UNAVAILABLE_TRY_LATER: 'DB_UNAVAILABLE_TRY_LATER',

  // INTERNAL_*
  INTERNAL_UNKNOWN: 'INTERNAL_UNKNOWN',
  INTERNAL_DB_ERROR: 'INTERNAL_DB_ERROR',
  INTERNAL_TX_FAILED: 'INTERNAL_TX_FAILED',
  INTERNAL_ASSERTION: 'INTERNAL_ASSERTION',
} as const;

export type AppErrorCodeType = (typeof AppErrorCode)[keyof typeof AppErrorCode];
