// Stable audit action enum. Values MUST align with Prisma AuditAction enum.
// Only append new values; do not rename or remove existing ones.

export const AuditActionEnum = {
  USER_CREATED: 'USER_CREATED',
  USER_LANGUAGE_CHANGED: 'USER_LANGUAGE_CHANGED',
  PROFILE_DRAFT_CREATED: 'PROFILE_DRAFT_CREATED',
  PROFILE_DRAFT_UPDATED: 'PROFILE_DRAFT_UPDATED',
  PROFILE_CONFIRMED: 'PROFILE_CONFIRMED',
  PROFILE_PAUSED: 'PROFILE_PAUSED',
  PROFILE_RESUMED: 'PROFILE_RESUMED',
  PROFILE_DELETED: 'PROFILE_DELETED',
  COMPANY_VERIFIED: 'COMPANY_VERIFIED',
  JOB_DRAFT_CREATED: 'JOB_DRAFT_CREATED',
  JOB_CONFIRMED: 'JOB_CONFIRMED',
  JOB_CLAIMED: 'JOB_CLAIMED',
  JOB_CLOSED: 'JOB_CLOSED',
  JOB_PUBLISHED_FROM_CRAWL: 'JOB_PUBLISHED_FROM_CRAWL',
  INTEREST_RECORDED: 'INTEREST_RECORDED',
  INTEREST_ACCEPTED: 'INTEREST_ACCEPTED',
  INTEREST_DECLINED: 'INTEREST_DECLINED',
  INTEREST_WITHDRAWN: 'INTEREST_WITHDRAWN',
  INTEREST_EXPIRED_PAUSED: 'INTEREST_EXPIRED_PAUSED',
  MATCH_CREATED: 'MATCH_CREATED',
  MATCH_ENDED: 'MATCH_ENDED',
  MATCH_BLOCKED: 'MATCH_BLOCKED',
  CONTACT_OPENED: 'CONTACT_OPENED',
  NOTIFY_QUEUED: 'NOTIFY_QUEUED',
  NOTIFY_SUCCEEDED: 'NOTIFY_SUCCEEDED',
  NOTIFY_FAILED_DEAD: 'NOTIFY_FAILED_DEAD',
  CRAWL_RUN_STARTED: 'CRAWL_RUN_STARTED',
  CRAWL_RUN_FINISHED: 'CRAWL_RUN_FINISHED',
  CRAWL_SOURCE_REGISTERED: 'CRAWL_SOURCE_REGISTERED',
  CRAWL_JOB_DISCOVERED: 'CRAWL_JOB_DISCOVERED',
  CRAWL_JOB_PARSED: 'CRAWL_JOB_PARSED',
  CRAWL_TRANSLATION_DONE: 'CRAWL_TRANSLATION_DONE',
  CRAWL_QA_FLAGGED: 'CRAWL_QA_FLAGGED',
  CRAWL_REVIEW_APPROVED: 'CRAWL_REVIEW_APPROVED',
  CRAWL_REVIEW_REJECTED: 'CRAWL_REVIEW_REJECTED',
  CRAWL_JOB_PUBLISHED: 'CRAWL_JOB_PUBLISHED',
  CRAWL_JOB_MARKED_STALE: 'CRAWL_JOB_MARKED_STALE',
  SOURCE_DISCOVERED: 'SOURCE_DISCOVERED',
  SOURCE_IMPORTED: 'SOURCE_IMPORTED',
  SOURCE_VALIDATED: 'SOURCE_VALIDATED',
  SOURCE_APPROVED: 'SOURCE_APPROVED',
  SOURCE_REJECTED: 'SOURCE_REJECTED',
  SOURCE_SUSPENDED: 'SOURCE_SUSPENDED',
  SOURCE_DEFERRED: 'SOURCE_DEFERRED',
  JOB_DEFERRED: 'JOB_DEFERRED',
  JOB_RETRANSLATED: 'JOB_RETRANSLATED',
  MATCH_INTERESTED_CANDIDATE: 'MATCH_INTERESTED_CANDIDATE',
  MATCH_INTERESTED_COMPANY: 'MATCH_INTERESTED_COMPANY',
  MATCH_CONTACT_OPENED: 'MATCH_CONTACT_OPENED',
  CANDIDATE_STATUS_CHANGED: 'CANDIDATE_STATUS_CHANGED',
  COMPANY_JOB_STATUS_CHANGED: 'COMPANY_JOB_STATUS_CHANGED',
  TRUST_REPORT_SUBMITTED: 'TRUST_REPORT_SUBMITTED',
  TRUST_BLOCK_EFFECTIVE: 'TRUST_BLOCK_EFFECTIVE',
  REMOTE_SOURCE_SYNCED: 'REMOTE_SOURCE_SYNCED',
  REMOTE_JOB_NORMALIZED: 'REMOTE_JOB_NORMALIZED',
  REMOTE_ELIGIBILITY_CHECKED: 'REMOTE_ELIGIBILITY_CHECKED',
  REMOTE_DAILY_DIGEST_SENT: 'REMOTE_DAILY_DIGEST_SENT',
  JOB_APPLICATION_STATUS_CHANGED: 'JOB_APPLICATION_STATUS_CHANGED',
  FOLLOW_UP_REMINDER_SENT: 'FOLLOW_UP_REMINDER_SENT',
} as const;

export type AuditActionType = (typeof AuditActionEnum)[keyof typeof AuditActionEnum];

// Sanity keys allowed in audit metadata. We never validate against this at runtime
// (it's a defense-in-depth guide for humans writing audit events).
export const AUDIT_METADATA_SAFE_KEYS = new Set<string>([
  'actor_side',
  'affected_object',
  'ai_provider_id',
  'attempts',
  'candidate_id',
  'candidate_version',
  'changed_fields',
  'confirm_count',
  'cv',
  'draft_source',
  'draft_version',
  'error_count',
  'field_count',
  'from',
  'hashed_confirm_token',
  'initial_language',
  'interest_id',
  'interest_pair',
  'jv',
  'job_id',
  'job_version',
  'match_id',
  'method',
  'new_count',
  'new_version',
  'notification_id',
  'object_type',
  'parse_version',
  'reason',
  'reason_code',
  'recipient_id',
  'report_id',
  'role',
  'scope',
  'sharer_sides',
  'source',
  'source_id',
  'source_job_id',
  'source_type',
  'status',
  'target_id',
  'target_type',
  'telegram_user_id_hash',
  'to',
  'type',
  'warnings_count',
  'degraded',
  'changed_count',
  'closed_count',
  'translated_count',
  'review_required_count',
  'snapshot_id',
  'staging_job_id',
  'translation_language',
  'translation_provider',
  'qa_flags',
  'parser_type',
  'parser_version',
  'detected_language',
  'reject_reason_code',
  'http_status',
  'blocker_id',
  'company_id',
  'base_url',
  'jobs_url',
  'review_status',
  'discovery_method',
  'city',
  'industry',
  'verification_score',
  'verification_notes',
  'validation_error',
  'import_row',
  'dry_run',
  'old_status',
  'new_status',
  'deferred_until',
  'defer_reason',
  'retranslation_trigger',
  'retranslation_provider',
  'match_status_before',
  'opened_by_side',
  'job_search_status',
  'company_job_status',
  'from_jt_match',
  'status_source',
]);
