-- 0007_approval_and_lifecycle
-- Approval center + job lifecycle + match + audit actions expansion
-- All statements MUST be idempotent.

DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SOURCE_DEFERRED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOB_DEFERRED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOB_RETRANSLATED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MATCH_INTERESTED_CANDIDATE';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MATCH_INTERESTED_COMPANY';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'MATCH_CONTACT_OPENED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CANDIDATE_STATUS_CHANGED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'COMPANY_JOB_STATUS_CHANGED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- CrawlJobStatus new values
DO $$ BEGIN
  ALTER TYPE "CrawlJobStatus" ADD VALUE IF NOT EXISTS 'DEFERRED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "CrawlJobStatus" ADD VALUE IF NOT EXISTS 'PAUSED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "CrawlJobStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TYPE "CrawlJobStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- SourceReviewStatus new value DEFERRED
DO $$ BEGIN
  ALTER TYPE "SourceReviewStatus" ADD VALUE IF NOT EXISTS 'DEFERRED';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE IF EXISTS source_registry
  ADD COLUMN IF NOT EXISTS suspended_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS source_registry
  ADD COLUMN IF NOT EXISTS disable_reason VARCHAR(1024);

ALTER TABLE IF EXISTS crawl_jobs_staging
  ADD COLUMN IF NOT EXISTS expiry_date TIMESTAMPTZ;
ALTER TABLE IF EXISTS crawl_jobs_staging
  ADD COLUMN IF NOT EXISTS last_confirmed_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS crawl_jobs_staging
  ADD COLUMN IF NOT EXISTS closed_reason VARCHAR(1024);

ALTER TABLE IF EXISTS jobs
  ADD COLUMN IF NOT EXISTS expiry_date TIMESTAMPTZ;
ALTER TABLE IF EXISTS jobs
  ADD COLUMN IF NOT EXISTS last_confirmed_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS jobs
  ADD COLUMN IF NOT EXISTS closed_reason VARCHAR(1024);
