ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "industry" VARCHAR(128);
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "size" VARCHAR(64);
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "location" VARCHAR(256);
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "recruiter_name" VARCHAR(256);
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "recruiter_role" VARCHAR(128);
