DO $$ BEGIN
    ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CRAWL_AUTO_PUBLISH_TRIGGERED';
EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END $$;

DO $$ BEGIN
    ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CRAWL_AUTO_PUBLISH_SKIPPED';
EXCEPTION WHEN duplicate_object THEN NULL; WHEN others THEN NULL; END $$;
